### ISSUE TITLE
Backlog of pull requests

### ISSUE THREAD

**Issue by LaurierMantel** [justinthec/uwhksa#6]
It seems to me that there are a number of productive pull requests ready to be merged.  We should get these shipped so we don't hold other people up, and so we can stay scrappy and meet our deadlines.  

Let's regroup and discuss ASAP @justinthec @jonathankwok @jules2689 @karanthukral :smile_cat: :dancer:

**Comment by jules2689** [comment]
You're right @LaurierMantel . It is kind of tedious considering we aren't even collaborators. Might I suggest the Repo Owner engage in a more engaging form of communication?
