### ISSUE TITLE
Roadmap is unclear, README is non-existant

### ISSUE THREAD

**Issue by jules2689** [justinthec/uwhksa#7]
Looking at the webpage, and its _issues_, it is apparent there is some work left to do. However, there is no mention of a roadmap and no issues to track anything.

There isn't even a README. How do I set this repo up? How do I get the dev environment in order? How would you expect to use this in a future merit-based application at a large company without a README?

I'd like to ask that a roadmap be clearly made in the issue tracker or a Trello board, depending on what Team Lead @justinthec decides is best. Also, a proper README would be really helpful!

Let's look at this together. @justinthec @jonathankwok @jules2689 @karanthukral :smile_cat: :dancer:
I think we're quite red at this point :heart: #gsd

**Comment by LaurierMantel** [comment]
I agree.  Alignment is :red_circle: ATM.

**Comment by Nosajool** [comment]
:+1: Also need to set up CI to support the influx of open PRs
