### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jules2689** [justinthec/uwhksa#8]
The author doesn't seem to want to maintain the project at all.
Is this project dead?

cc @justinthec @jonathankwok @LaurierMantel

**Comment by LaurierMantel** [comment]
Cc @karanthukral for sure on this one.

**Comment by LaurierMantel** [comment]
I'd say either kill the project or open it up to new collaborators.  Full rewrite may be necessary @jules2689 what do you think?

**Comment by jules2689** [comment]
Ah yes, karan's user wasn't autocompleting. Perhaps @Nosajool has some input too.

**Comment by LaurierMantel** [comment]
Yup.  @kyewei has worked with the author before and we could probably use his judgement.  So has @branchow.

**Comment by karanthukral** [comment]
This project should be up for grabs if the original maintainer is moving on!

**Comment by LaurierMantel** [comment]
https://github.com/LaurierMantel/uwhksa

We can collaborate here.

**Comment by LaurierMantel** [comment]
I also reinitialized the .git folder ^ so we won't have references to the poor work culture of this project

**Comment by Nosajool** [comment]
Missing README. What's a uwhksa?

**Comment by justinthec** [comment]
you guys are real big fugs

**Comment by jules2689** [comment]
Not how I'd expect an owner to act:
![image](https://cloud.githubusercontent.com/assets/3074765/17454796/9764ff90-5b71-11e6-8f7a-e6aca3087fde.png)
